apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: risa-infra
data:
  rabbitmq.conf: |
    default_user = admin
    default_pass = admin123
    loopback_users.guest = false
    management.load_definitions = /etc/rabbitmq/definitions.json
