apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: database
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: supersecret
  AUTH_DB_PASSWORD: auth_secret
  BILLING_DB_PASSWORD: billing_secret