apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  namespace: gateway
  labels:
    app: gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
      - name: gateway-api
        image: noooksd/gateway-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: gateway-secret
              key: Jwt__Key
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: gateway-secret
              key: RabbitMq__Password
        volumeMounts:
        - name: config
          mountPath: /app/appsettings.Production.json
          subPath: appsettings.json
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: gateway-config
          items:
          - key: appsettings.json
            path: appsettings.json