apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: gateway
type: Opaque
stringData:
  Jwt__Key: "your-super-secret-key-min-32-chars-long-change-in-production"
  RabbitMq__Password: "admin123"